### ISSUE TITLE
Reason behind no anonymous donors for funding?

### ISSUE THREAD

**Issue by cryptnotiq** [virgo-project/virgo#10]
In FUNDING.md it states no anonymous donors. Why is this?
I understand that the only "reward" to expect is public recognition, but what if someone/organisation does not care of the public recognition and solely wants to support a good cause? Is it a legal aspect with KYC/AML?

**Comment by jaekwon** [comment]
No, it's because I believe anonymous donations can be used to promote a hidden agenda, e.g. what if campaign contributions were contributed by shady shell corps funded by an enemy of the state?

I reject it on principle but am open to ideas to mitigate this concern.
