### ISSUE TITLE
Thoughts on Signal

### ISSUE THREAD

**Issue by jaekwon** [virgo-project/virgo#12]
* Groups don't work well
* It exposes phone numbers
* You can't export your data.

**Comment by marbar3778** [comment]
> - You can't export your data.

Why would you want to export the data? I feel this would be breach of trust of the participant(s), unless everyone is notified that this person is exporting data and they can vote to approve it

- I'd like to hear your thoughts on notifying/preventing the participant(s) from taking a screenshot. 

In chats, people regularly take screenshots of conversations and many times they don't take the whole conversation so the person seeing the screenshot doesn't know the full context and is being guided by the person who took the screenshot and can create assumptions of the other participants.

**Comment by zmanian** [comment]
I have some history with this.

Signal was designed to make life difficult for an attacker who might have physical access to your device but can't unlock it.
https://twitter.com/fredericjacobs/status/702523823623643136?lang=en

Fixing the phone number thing is on the roadmap.

I've gone back and forth with the Signal devs about what kinds of guarantees disappearing messages should provide.

It's possible to provide a notification if another user does a screenshot but that's trivial to defeat by compiling your own signal app. This is a tough problem to solve in an open source context.

**Comment by shanev** [comment]
We are seeing an interesting convergence between Twitter and Signal/Telegram. Twitter's DM functionality now has groups, yet still limited compared to Telegram. But over time it will catch up. At the same time some popular Twitter folks (like om and naveen) now have Telegram groups. Therefore, if you extrapolate into the future, I believe #23 and DMs/groups should be part of the same service, at least at the client level. 

Maybe there should be some common "social hub" that connects all types of social apps.

**Comment by haymond** [comment]
I like that idea @shanev. It reminds me of an open-source Trillian for social apps. 

If this is a direction the Virgo team decides to go, it'll be interesting to see what the incentives are for teams like [Desmos](https://www.desmos.network/), which we'll be meeting with soon.

**Comment by cwgoes** [comment]
Moxie's 36c3 [talk](https://peertube.co.uk/videos/watch/12be5396-2a25-4ec8-a92a-674b1cb6b270) explains much of the design rationale behind Signal in detail - many points worth considering when designing chat systems (especially encrypted and/or decentralised ones).

**Comment by andyboyan** [comment]
Status.im will be releasing v1 of the app in February sometime. It is a replacement for Signal that does not require any phone number or any identifying information for messaging. Group chat is ok on it, but it is better for fewer than 5 in a group chat unless people use .ens names.
