### ISSUE TITLE
centralized power structure?

### ISSUE THREAD

**Issue by hschoenburg** [virgo-project/virgo#2]
Isn't it ironic and fairly off-brand that Virgo's sole executive is also its sole board member?
This current structure seems off for an org dedicated to DAOs and also not in alignment with its stated core values 

Accountable? 
Democratic?

**Comment by jaekwon** [comment]
I'm being transparent about the state of this project and who decides what the mark "VIRGO" is about, and how the funds will be distributed.

What I want to do is create a permissioned body of people (the "founders"), some constant C new members based on proof-of-work, where the work is contributions to this repo that prove some sort of vision/values alignment, capability, and rationality.

Then, I think this group would naturally decide to further expand the founders group via an invitation system, but I'm getting ahead of myself here.

I'm also open to other ideas, but I want to make sure that decentralization happens in the *right* way, and merely ensure that I agree with the initial direction of decentralization.  Everyone is free to fork this repo and do it with a different brand and their own sources funding, if they disagree with my opinions on how to decentralize Virgo.  Which is all very consistent with the Virgo values IMO.

This group of founders would have equal votes, and we would collectively be responsible for finalizing the manifesto and signing it.  Of course the founders isn't everyone on earth, so it's not a global democracy system, but we have to start somewhere and take in phases.

Much of this is in my head and have not yet been written so please bear with me as I react to these questions.  Keep them coming, and please provide constructive feedback.

And be bloody honest.  I can handle the truth.

**Comment by jaekwon** [comment]
It makes all the sense in the world to commit to C and a time-frame, but I don't know what is optimal.  Maybe C=2, 4, or 6 to get started, then from there we can decide on a plan to get to say 20 or 100 or so.

**Comment by faddat** [comment]
Brutal honesty:

RChain was focused on social coordination and democracy and saving the world/environment.  They used those "social coordination goals" as a shield for every kind of corruption imaginable.    Look where that got e'm.  I'm not fully convinced we have an environmental problem.  

But certainly we have an intellectual property and free speech problem.  Intellectual property is morally bankrupt.  We need open, modular hardware very badly. 

Now that I've dispensed with that, I freaking love this concept!

I don't quite know what shape it will take it almost seems like Virgo is connected to the stardust chain that I read about earlier as well?

I'd like to do some virgo ruminations on social media and on open hardware, too.  

Will continue this tomorrow, maybe with a controversial PR. Goodnight!
