### ISSUE TITLE
Thoughts on Mastodon

### ISSUE THREAD

**Issue by nylira** [virgo-project/virgo#23]
[Mastodon](https://mastodon.social) is a decentralized, self-hosted, open source alternative to Twitter. We should investigate Mastodon's UI to see if it can be repurposed for our needs. Specifically, we would need to add these features:

* uncensorable, decentralized backend, likely blockchain
* governance component that lets community members vote
* veracity component that lets the community vote on the truthiness of news

**Comment by shanev** [comment]
The biggest I see with Mastodon and other federated approaches is people have to chose which server to join. Although it would be great to have a specific sever for something like "Crypto Twitter", it prevents cross-pollination of ideas and thoughts.
