### ISSUE TITLE
Should Virgo recordings be upload to YouTube? 

### ISSUE THREAD

**Issue by haymond** [virgo-project/virgo#34]
[Here is the recording](https://drive.google.com/file/d/140z21Mz4j12QCnkZgVlR96OoYYrmOOcy/view?usp=sharing) from this week's Virgo meeting. Before I add it to the new project management folder #33 which will have meeting notes/agenda/recordings, should this be uploaded on a YouTube channel? Right now I'm uploading it to my work Google Drive.

**Comment by nylira** [comment]
Yes I think they should, with an opening card and ending card!

**Comment by haymond** [comment]
Sounds good. Should these recordings go on the Cosmos YouTube channel in a different playlist or a completely separate channel? My thinking is a separate channel but I'd love to hear others thoughts.

**Comment by haymond** [comment]
Awesome! That sounds good. I uploaded this weeks talk after figuring out how to upload longer videos on YouTube. It's currently unlisted and we can make it public once the cards are done.

**Comment by adrianakalpa** [comment]
Can all topics discussed in the townhall be made public? We brought up some names, amounts or rewards/compensation. Is this something we want to make public in this early stage of the discussion?

**Comment by haymond** [comment]
That's a really good point @adrianakalpa. Let's discuss more on Slack
