### ISSUE TITLE
Projects for the Virgo Directory

### ISSUE THREAD

**Issue by nylira** [virgo-project/virgo#41]
The last of the year's Virgo town hall discussed having a directory of projects that align with Virgo's vision. I wanted to get this started! What organizations can we start with, and what organizations can we quickly get onboard? @haymond @Michelle-L

Preliminary list:
* Interchain Foundation
* Cosmos
* Tendermint Inc

Reach out opportunities:
* Aragon (Michelle)
* DAOStack (?)
* Ecosia (Michelle)

**Comment by haymond** [comment]
Thanks for taking the initiative here Peng. I can reach out to these orgs and get their feedback. 

- [MolachDAO](https://molochdao.com/) 

- [StakerDAO](https://www.stakerdao.com/)
