### ISSUE TITLE
Limits on Board/Executive positions across multiple DAOs

### ISSUE THREAD

**Issue by cryptnotiq** [virgo-project/virgo#9]
Any ideas on if and how to approach limiting the number of positions someone can have on multiple DAOs?

Simply, we could choose to go with a limit of 1 position in each across the ecosystem. However, I think that severely limits potential (at least initially until we have a critical, mainstream, userbase).

Otherwise I believe that in connected DAOs, i.e ones that serve a similar purpose/interact with each other frequently/are either used to enforce, oversee, or otherwise influence/regulate each other should have a 1 position ( executive, board) limit. 

And impose lenient limits (if any) on DAOs that are not directly related to each other, even though they are all working together to achieve the same vision. Like a second or third degree of separation vastly reduces or eliminates limits.

**Comment by nestmiron** [comment]
I believe that a balance should be found between avoiding any limitation that could reduce the potential contributions of these members and the corruption that might arise from occupying prominent positions in several DAOs at the same time.

Ideally, a person should occupy only one position. But I suppose it is a difficult ideal to achieve, especially at the beginning.
